### ISSUE TITLE
Presently shows optimal bs for the virtual mem "device"

### ISSUE THREAD

**Issue by tukoz** [tdg5/blog#1]
First, thanks for your paper on this; I liked reading it! Actually 'been some time since it was on my TODO list; which happened today --viva summer time :-)

It seems both of your tests are letting the kernel page cache or virtual memory subsystem takes the lead. It's kind of clearer on the "find out optimal _input_ block size", so I'll report here. Apologies for doing so before I could dig in your scripts.

1) On a fast USB stick (ok fast _but_)

```
$ ./dd_ibs_test.sh /media/SDX64_2/dd_ibs_testfile                                                                                                                                                                                    
Generating test file...
block size : transfer rate
     512 : 894 MB/s
    1024 : 1 GB/s
    2048 : 4 GB/s
    4096 : 6 GB/s
    8192 : 5 GB/s
   16384 : 0 GB/s
   32768 : 3 GB/s
   65536 : 2 GB/s
  131072 : 3 GB/s
  262144 : 1 GB/s
  524288 : 1 GB/s
 1048576 : 9 GB/s
 2097152 : 9 GB/s
 4194304 : 7 GB/s
 8388608 : 4 GB/s
16777216 : 0 GB/s
33554432 : 3 GB/s
67108864 : 9 GB/s
```

2) On SSD

```
$ sh $HOME/.local/scripts/dd_ibs_test.sh ~/dd_ibs_testfile                                                                                                                                                                                    
Generating test file...
block size : transfer rate
     512 : 896 MB/s
    1024 : 7 GB/s
    2048 : 0 GB/s
    4096 : 9 GB/s
    8192 : 5 GB/s
   16384 : 9 GB/s
   32768 : 4 GB/s
   65536 : 6 GB/s
  131072 : 8 GB/s
  262144 : 5 GB/s
  524288 : 9 GB/s
 1048576 : 7 GB/s
 2097152 : 8 GB/s
 4194304 : 7 GB/s
 8388608 : 1 GB/s
16777216 : 8 GB/s
33554432 : 5 GB/s
67108864 : 8 GB/s
```

Test system: Ivy 3.3 GHz with Arch Linux.
Linux llewellyn 4.7.2-1-ck #1 SMP PREEMPT Sat Aug 20 14:07:40 EDT 2016 x86_64 GNU/Linux

**Comment by tdg5** [comment]
Hey @tukoz!

I pushed out some updates this morning that update the scripts to clear the kernel cache on every iteration and also force dd to use `fsync` mode which should make it skip the fs cache and actually write the blocks to disk before declaring itself done. I think these changes should address your concerns. If not, please let me know and I can reopen this issue.

Thanks for the feedback!
