### ISSUE TITLE
Unexpected operator

### ISSUE THREAD

**Issue by sup2069** [tdg5/blog#4]
Running the script runs with the following error:

> sup2069@debian-pc:~$ sudo sh scripts/dd.obs.test.sh /dev/null
> scripts/dd.obs.test.sh: 17: [: -ne: unexpected operator
> block size : transfer rate
> scripts/dd.obs.test.sh: 37: [: -eq: unexpected operator

When omitting the cache clear (using your website script from 2015, it works). http://blog.tdg5.com/tuning-dd-block-size/

**Comment by voidxor** [comment]
@sup2069 I'm still kind of new to Linux scripts, but aren't the `-ne` (not equal) and `-eq` (equal) operators specific to bash? If you're forcibly executing the script with sh, or whatever that is an alias of on your system (e.g. dash), bash-specific stuff might not work.

Try executing with `sudo ./scripts dd.obs.test.sh /dev/null` such that the `#! /bin/bash` hash bang is not overridden.

**Comment by sup2069** [comment]
Closing, no longer pursuing this. Thanks.
